# Generated by Django 3.2.8 on 2021-10-28 17:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='نام')),
                ('lastname', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('landline_phone', models.CharField(max_length=100, verbose_name='تلفن ثابت')),
                ('mobile', models.CharField(max_length=100, verbose_name='موبایل')),
                ('device_password', models.CharField(max_length=200, verbose_name='رمز عبور دستگاه')),
                ('acceptor_name', models.CharField(max_length=200, verbose_name='نام پذیرنده دستگاه')),
                ('name_of_services', models.CharField(max_length=100, verbose_name='نام سرویس کار')),
                ('the_name_of_the_final_tester', models.CharField(max_length=100, verbose_name='نام تستر نهایی')),
                ('accessories', models.CharField(max_length=200, verbose_name='لوازم جانبی')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='شماره فاکتور')),
                ('operations_performed_on_the_device', ckeditor.fields.RichTextField()),
                ('received_money', models.CharField(max_length=100, verbose_name='مبلغ دریافتی')),
                ('startdatetime', models.DateTimeField(verbose_name='تاریخ و زمان')),
                ('call_status', models.IntegerField(choices=[('ok', 'تماس گرفته شد'), ('off', 'خاموش بود'), ('he_was_not_accountable', 'پاسخگو نبودند')], verbose_name='وضعیت تماس')),
            ],
            options={
                'verbose_name': 'ثبت مشتری ',
                'verbose_name_plural': 'ثبت مشتری ',
            },
        ),
    ]
