# Generated by Django 3.2.8 on 2021-10-28 18:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregistration',
            name='operations_performed_on_the_device',
            field=ckeditor.fields.RichTextField(verbose_name='عملیات انجام شده بر روی دستگاه'),
        ),
    ]
