# Generated by Django 3.2.8 on 2021-10-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_customerregistration_operations_performed_on_the_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregistration',
            name='call_status',
            field=models.CharField(choices=[('ok', 'تماس گرفته شد'), ('off', 'خاموش بود'), ('he_was_not_accountable', 'پاسخگو نبودند')], max_length=100, verbose_name='وضعیت تماس'),
        ),
    ]
