# Generated by Django 3.2.8 on 2021-10-30 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_customerregistration_call_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregistration',
            name='startdatetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاریخ و زمان'),
        ),
    ]
