# Generated by Django 3.2.8 on 2021-11-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_customerregistration_startdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregistration',
            name='landline_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='تلفن ثابت'),
        ),
    ]
