# Generated by Django 3.2.8 on 2021-11-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_customerregistration_landline_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregistration',
            name='accessories',
            field=models.CharField(blank=True, max_length=200, verbose_name='لوازم جانبی'),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='device_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='رمز عبور دستگاه'),
        ),
    ]
